default:
  image: node:16-buster-slim

cache:
  paths:
    - .yarn

stages:
  - install
  - test
  - build
  - deploy

install-dependencies:
  stage: install
  script:
    - yarn install --frozen-lockfile
  cache:
    key: 
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull-push

testing:
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn test
    - echo "All tests pass!"
  cache:
    key: 
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull

build-frontend:
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - echo "Project build successful!"
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull
  artifacts:
    paths:
      - ./frontend/build

deploy-int-stable:
  image: ruby:3.1.2-bullseye
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$CYOA_APP_INT_STABLE --api-key=$DEPLOYMENT_KEY

deploy-production:
  image: ruby:3.1.2-bullseye
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$CYOA_APP_PROD --api-key=$DEPLOYMENT_KEY
  only:
    - master
