default:
  image: node:16-buster-slim

cache:
  file:
    - yarn.lock
  paths:
    - node_modules

stages:
  - install
  - build
  - deploy

install-dependencies:
  stage: install
  script:
    - yarn install --frozen-lockfile
  cache:
    key: 
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull-push

build-frontend:
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - echo "Project build successful!"
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull
  artifacts:
    paths:
      - build

deploy-int-stable:
  image: ruby:3.1.2-bullseye
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$CYOA_APP_INT_STABLE --api-key=$DEPLOYMENT_KEY

deploy-production:
  image: ruby:3.1.2-bullseye
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$CYOA_APP_PROD --api-key=$DEPLOYMENT_KEY
  only:
    - master
